FROM dxflrs/garage:v1.0.1 AS garage
FROM alpine:3.20
COPY --from=garage /garage /usr/local/bin/garage
COPY garage-init.sh /usr/local/bin/garage-init.sh
RUN chmod +x /usr/local/bin/garage-init.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/garage-init.sh"]
